### ISSUE TITLE
Reverie Receptor Missing

### ISSUE THREAD

**Issue by saintnoodle** [malulleybovo/PSO2AffixingAssistant#62] opened 2021-04-28 06:22 UTC
Unable to select Reverie Receptor when transferring Mana Reverie.

**Comment by malulleybovo** [comment] 2021-04-28 12:49
Thank you for reporting. Which link did you use to reproduce this issue? Since v1.3.0 of the Assistant, it does have the option to use reverie receptor. It might be that the link is from an outdated fork of the project. Please try this link: https://malulleybovo.github.io/PSO2AffixingAssistant/?glen2/ujQ_ln8Hyshe.e2.

**Comment by malulleybovo** [comment] 2021-04-28 12:52
I’ll be closing the issue since it seems not to be present in the Assistant (main repository - malulleybovo.github.io). If you believe the issue is still present, please provide more evidence on how to reproduce the issue.

**Closed as completed by malulleybovo** 2021-04-28 12:52 UTC
Labels: invalid
