### ISSUE TITLE
Exceed receptor conflicts with a multitude (possibly all?) non-junk affixes.

### ISSUE THREAD

**Issue by Kamil118** [malulleybovo/PSO2AffixingAssistant#51] opened 2021-01-22 00:31 UTC
**Describe the bug**
Exceed receptor conflicts with a multitude (possibly all?) non-junk affixes.

Confirmed conflicts:
Empy Embrace
Vol Soul
Might III
Elder Reverie
Lesser Spirit V
Lesser Might V
S3: Luminous Grace
Exceed Energy
Crack V
Arks Fever
S3:Junk

**To Reproduce**
Create any recipe that attempts to affix Exceed energy
Example of recipe that was used to test most of the conflicts listed above: https://bit.ly/395WtLu

**Expected behavior**
Exceed receptor should only conflict with other receptor affixes

**Comment by Kamil118** [comment] 2021-01-23 01:29
I just realized that the link to bug report in corvus fork leads here.

Tested on your version, the issue is here as well. Exemplary recipe in this version: https://bit.ly/39Xx71j

**Comment by malulleybovo** [comment] 2021-02-13 04:52
Thank you for reporting. By my initial investigation, that appears to be due a design decision made in the beginning of the Assistant: prevent users from making formulas containing fodders highly unlikely to be dropped or bought. That was during the era of the Soul Receptors, which were fairly hard to drop or buy (for a reasonable price) with a specific configuration (containing a specific Soul, etc.). This has been changing for a good while now with more Receptors added and more combinations of abilities in Fodders containing Receptor. This one might take a bit longer to change since it delves deeper into the inner workings of the Assistant, but it will be on the radar.

**Comment by malulleybovo** [comment] 2021-04-25 05:06
Closing as duplicate of https://github.com/malulleybovo/PSO2AffixingAssistant/issues/49. Please head to that issue for further updates on the matter.

**Closed as completed by malulleybovo** 2021-04-25 05:06 UTC
Labels: enhancement
