### ISSUE TITLE
Plus and minus Material Slots is missing

### ISSUE THREAD

**Issue by Inabi-Ibani** [malulleybovo/PSO2AffixingAssistant#42] opened 2020-10-17 13:07 UTC
**Describe the bug**
Plus and minus Material Slots(https://i.imgur.com/SR6Bu1V.png)is missing when an SSA is not present, even if "add ability item" is used. It simply adds "Junk x" with no way to remove it.

**Screenshots**
https://i.imgur.com/2a7wvkR.png

**Comment by 3geek14** [comment] 2020-10-20 21:50
I came here to report the same bug, but saw Inabi already did so.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'check or change the affixing goal'
2. Click on 'Might I' and 'Precision VI'
3. Click on 'Transfer'
4. Click on 'Select' under 'Add Mastery Item', then click 'Precision VI'.
4. See error

**Expected behavior**
There should be an option to have the fodder have only 1 augment (Might I), as in Inabi's first screenshot.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by ionizer** [comment] 2020-11-09 07:54
Looks like it would be a simple fix on this [location](https://github.com/malulleybovo/PSO2AffixingAssistant/blob/d7ab31eca26ed612f4b450b612a92cde87e2c47e/js/templates.js#L458) (templates.js, line 458) by adding another condition into the `if`, maybe (either `addAbilityChosen` or `addAbilityChoices.length > 0`). Right now it literally enables the slot adjustment option only when SSAs are present. I haven't got the time to test this yet unfortunately...

**Comment by 3geek14** [comment] 2020-11-09 14:13
You might have better luck finding the file that says what contributions are accepted. This is not one.

**Comment by ionizer** [comment] 2020-12-09 19:45
I can confirm that the changes has been made and is fixed after the merge of #45. We should be able to close this issue.

**Comment by malulleybovo** [comment] 2021-01-11 03:04
Issue has been fixed in v1.2.2.

**Closed as completed by malulleybovo** 2021-01-11 03:04 UTC
