### ISSUE TITLE
Issue with "VIEW FODDERS NEEDED"

### ISSUE THREAD

**Issue by FariusDAG** [malulleybovo/PSO2AffixingAssistant#1] opened 2018-11-18 18:07 UTC
**Describe the bug**
When you make an affix and click the "View Fodders Needed" option, you can see it tells you which fodders you'll need. If then you do an "Affix It" option to any of the fodders, and make a new branch with new fodder to make the first one, when you check the "View Fodders Needed" again, it will only tell you the fodders needed for that new branch. 

**To Reproduce**
1. Make any affix plan.
2. Click the "Affix it" option in any of them and make the plan for that fodder.
3. Press "View fodders needed".
4. It will only tell you the fodders needed for that last branch, forgetting about the other fodders from the main one.

**Screenshots**
![41c0634fc11e4269ecfc076f9f833f6a](https://user-images.githubusercontent.com/43413397/48676261-92fb4d80-eb64-11e8-8090-7dd2a1e53bb6.png)
![9c378413029885ef539a465d6a19f28a](https://user-images.githubusercontent.com/43413397/48676264-9ee70f80-eb64-11e8-81dc-8aacf19260f5.png)

                             ^
It correctly tells you which fodder you need.

![3c36878943f0400fb6865b7251f4ef09](https://user-images.githubusercontent.com/43413397/48676266-a3132d00-eb64-11e8-97a5-4f0492bb6909.png)
![93c4eac46cbbd5e04373cecbd05495dd](https://user-images.githubusercontent.com/43413397/48676269-a7d7e100-eb64-11e8-9f90-ee41aadea624.png)

                             ^
After adding an extra branch it forgets about the main one's fodder.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 70.0.3538.102 (Official Build) (64-bit)

**Additional context**
If you make more than one extra branch to make the fodders, when pressing "View Fodders Needed", it will tell you about those last new branches, not only the last one.

It's kinda hard to explain, hopefully you understand what im trying to say here.

Thanks for your great work!

**Comment by malulleybovo** [comment] 2018-11-19 02:51
The cause of the issue has been identified and it has been resolved. It was due to a wrong query in Assistant.getToBuyList. The fix was released in commit 8b012c20d8f6d6755c0ad8b22174bb767dc091f2.

**Closed as completed** 2018-11-19 06:55 UTC
Labels: bug
